package com.kodilla;

import java.util.ArrayList;
import java.util.Random;

public class GiveMe {

    static int randomInt(int digits){
        int result = 0;
        Random gen = new Random();
        for(int i = 0; i < digits; i++) {
            result += Math.pow(10,i) * gen.nextInt(9) + (i + 1 == digits ? 1 : 0);
        }
        return result;
    }



    static String randomFunnyTitle() {
        return randomName() + " " + randomLastName() + randomVerb() + randomAnimal() + randomConnector() + randomName();
    }

    static String randomJoinedAnimalName() {
        return randomAnimal().replace(" ","");
    }

    static String randomCompanyName() {
        return randomAnimal().replace(" ","") + randomCompanyType();
    }

    static String randomFullName() {
        return GiveMe.randomName() + " " + GiveMe.randomLastName();
    }

    static String randomIsbn() {
        Random gen = new Random();
        String isbn = 978 + "" + gen.nextInt(1000) + gen.nextInt(1000) + gen.nextInt(1000);
        Long checkIsbn = Long.parseLong(isbn)*1000000000;
        isbn = checkIsbn.toString().substring(0,12) + gen.nextInt(10);
        return isbn;
    }

    static String randomVerb() {
        ArrayList<String> verbs = new ArrayList<>();
        verbs.add(" ate ");
        verbs.add(" made ");
        verbs.add(" created ");
        verbs.add(" acted like ");
        verbs.add(" shaved ");
        verbs.add(" burned ");
        verbs.add(" sit on ");
        verbs.add(" locked ");
        verbs.add(" cracked ");
        verbs.add(" smashed ");
        verbs.add(" boiled ");
        verbs.add(" took care of ");
        verbs.add(" hold ");
        verbs.add(" sucked ");
        verbs.add(" smoked ");
        verbs.add(" fired up ");
        verbs.add(" made wet ");
        verbs.add(" jumped over ");
        verbs.add(" had date with ");
        verbs.add(" consumed ");
        verbs.add(" gave flowers to ");
        verbs.add(" caught ");
        verbs.add(" painted to pink color a ");
        verbs.add(" licked ");
        verbs.add(" slept with ");
        verbs.add(" abused ");
        return verbs.get(new Random().nextInt(verbs.size()));
    }

    static String randomCompanyType() {
        ArrayList<String> companyType = new ArrayList<>();
        companyType.add(" LTD.");
        companyType.add(" sp. Z.O.O.");
        companyType.add(" S.A.");
        companyType.add(" sp. j.");
        companyType.add(" sp. p.");
        companyType.add(" S.K.A.");
        companyType.add(" Partnership");
        companyType.add(" LLP.");
        companyType.add(" PLC.");
        return companyType.get(new Random().nextInt(companyType.size()));
    }

    static String randomConnector() {
        ArrayList<String> connectors = new ArrayList<>();
        connectors.add(" with ");
        connectors.add(" especially for ");
        connectors.add(" to impress ");
        connectors.add(" to disgrace ");
        connectors.add(" to win bet with ");
        connectors.add(" to take attention from ");
        connectors.add(" to seduce  ");
        return connectors.get(new Random().nextInt(connectors.size()));
    }

    static String randomLastName() {
        ArrayList<String> lastNames = new ArrayList<>();

        lastNames.add("Smith");
        lastNames.add("Johnson");
        lastNames.add("Williams");
        lastNames.add("Jones");
        lastNames.add("Brown");
        lastNames.add("Davis");
        lastNames.add("Miller");
        lastNames.add("Wilson");
        lastNames.add("Moore");
        lastNames.add("Taylor");
        lastNames.add("Anderson");
        lastNames.add("Thomas");
        lastNames.add("Jackson");
        lastNames.add("White");
        lastNames.add("Harris");
        lastNames.add("Martin");
        lastNames.add("Thompson");
        lastNames.add("Garcia");
        lastNames.add("Martinez");
        lastNames.add("Robinson");
        lastNames.add("Clark");
        lastNames.add("Rodriguez");
        lastNames.add("Lewis");
        lastNames.add("Lee");
        lastNames.add("Walker");
        lastNames.add("Hall");
        lastNames.add("Allen");
        lastNames.add("Young");
        lastNames.add("Hernandez");
        lastNames.add("King");
        lastNames.add("Wright");
        lastNames.add("Lopez");
        lastNames.add("Hill");
        lastNames.add("Scott");
        lastNames.add("Green");
        lastNames.add("Adams");
        lastNames.add("Baker");
        lastNames.add("Gonzalez");
        lastNames.add("Nelson");
        lastNames.add("Carter");
        lastNames.add("Mitchell");
        lastNames.add("Perez");
        lastNames.add("Roberts");
        lastNames.add("Turner");
        lastNames.add("Phillips");
        lastNames.add("Campbell");
        lastNames.add("Parker");
        lastNames.add("Evans");
        lastNames.add("Edwards");
        lastNames.add("Collins");
        lastNames.add("Stewart");
        lastNames.add("Sanchez");
        lastNames.add("Morris");
        lastNames.add("Rogers");
        lastNames.add("Reed");
        lastNames.add("Cook");
        lastNames.add("Morgan");
        lastNames.add("Bell");
        lastNames.add("Murphy");
        lastNames.add("Bailey");
        lastNames.add("Rivera");
        lastNames.add("Cooper");
        lastNames.add("Richardson");
        lastNames.add("Cox");
        lastNames.add("Howard");
        lastNames.add("Ward");
        lastNames.add("Torres");
        lastNames.add("Peterson");
        lastNames.add("Gray");
        lastNames.add("Ramirez");
        lastNames.add("James");
        lastNames.add("Watson");
        lastNames.add("Brooks");
        lastNames.add("Kelly");
        lastNames.add("Sanders");
        lastNames.add("Price");
        lastNames.add("Bennett");
        lastNames.add("Wood");
        lastNames.add("Barnes");
        lastNames.add("Ross");
        lastNames.add("Henderson");
        lastNames.add("Coleman");
        lastNames.add("Jenkins");
        lastNames.add("Perry");
        lastNames.add("Powell");
        lastNames.add("Long");
        lastNames.add("Patterson");
        lastNames.add("Hughes");
        lastNames.add("Flores");
        lastNames.add("Washington");
        lastNames.add("Butler");
        lastNames.add("Simmons");
        lastNames.add("Foster");
        lastNames.add("Gonzales");
        lastNames.add("Bryant");
        lastNames.add("Alexander");
        lastNames.add("Russell");
        lastNames.add("Griffin");
        lastNames.add("Diaz");
        lastNames.add("Hayes");
        lastNames.add("Myers");
        lastNames.add("Ford");
        lastNames.add("Hamilton");
        lastNames.add("Graham");
        lastNames.add("Sullivan");
        lastNames.add("Wallace");
        lastNames.add("Woods");
        lastNames.add("Cole");
        lastNames.add("West");
        lastNames.add("Jordan");
        lastNames.add("Owens");
        lastNames.add("Reynolds");
        lastNames.add("Fisher");
        lastNames.add("Ellis");
        lastNames.add("Harrison");
        lastNames.add("Gibson");
        lastNames.add("Mcdonald");
        lastNames.add("Cruz");
        lastNames.add("Marshall");
        lastNames.add("Ortiz");
        lastNames.add("Gomez");
        lastNames.add("Murray");
        lastNames.add("Freeman");
        lastNames.add("Wells");
        lastNames.add("Webb");
        lastNames.add("Simpson");
        lastNames.add("Stevens");
        lastNames.add("Tucker");
        lastNames.add("Porter");
        lastNames.add("Hunter");
        lastNames.add("Hicks");
        lastNames.add("Crawford");
        lastNames.add("Henry");
        lastNames.add("Boyd");
        lastNames.add("Mason");
        lastNames.add("Morales");
        lastNames.add("Kennedy");
        lastNames.add("Warren");
        lastNames.add("Dixon");
        lastNames.add("Ramos");
        lastNames.add("Reyes");
        lastNames.add("Burns");
        lastNames.add("Gordon");
        lastNames.add("Shaw");
        lastNames.add("Holmes");
        lastNames.add("Rice");
        lastNames.add("Robertson");
        lastNames.add("Hunt");
        lastNames.add("Black");
        lastNames.add("Daniels");
        lastNames.add("Palmer");
        lastNames.add("Mills");
        lastNames.add("Nichols");
        lastNames.add("Grant");
        lastNames.add("Knight");
        lastNames.add("Ferguson");
        lastNames.add("Rose");
        lastNames.add("Stone");
        lastNames.add("Hawkins");
        lastNames.add("Dunn");
        lastNames.add("Perkins");
        lastNames.add("Hudson");
        lastNames.add("Spencer");
        lastNames.add("Gardner");
        lastNames.add("Stephens");
        lastNames.add("Payne");
        lastNames.add("Pierce");
        lastNames.add("Berry");
        lastNames.add("Matthews");
        lastNames.add("Arnold");
        lastNames.add("Wagner");
        lastNames.add("Willis");
        lastNames.add("Ray");
        lastNames.add("Watkins");
        lastNames.add("Olson");
        lastNames.add("Carroll");
        lastNames.add("Duncan");
        lastNames.add("Snyder");
        lastNames.add("Hart");
        lastNames.add("Cunningham");
        lastNames.add("Bradley");
        lastNames.add("Lane");
        lastNames.add("Andrews");
        lastNames.add("Ruiz");
        lastNames.add("Harper");
        lastNames.add("Fox");
        lastNames.add("Riley");
        lastNames.add("Armstrong");
        lastNames.add("Carpenter");
        lastNames.add("Weaver");
        lastNames.add("Greene");
        lastNames.add("Lawrence");
        lastNames.add("Elliott");
        lastNames.add("Chavez");
        lastNames.add("Sims");
        lastNames.add("Austin");
        lastNames.add("Peters");
        lastNames.add("Kelley");
        lastNames.add("Franklin");
        lastNames.add("Lawson");
        lastNames.add("Fields");
        lastNames.add("Gutierrez");
        lastNames.add("Ryan");
        lastNames.add("Schmidt");
        lastNames.add("Carr");
        lastNames.add("Vasquez");
        lastNames.add("Castillo");
        lastNames.add("Wheeler");
        lastNames.add("Chapman");
        lastNames.add("Oliver");
        lastNames.add("Montgomery");
        lastNames.add("Richards");
        lastNames.add("Williamson");
        lastNames.add("Johnston");
        lastNames.add("Banks");
        lastNames.add("Meyer");
        lastNames.add("Bishop");
        lastNames.add("Mccoy");
        lastNames.add("Howell");
        lastNames.add("Alvarez");
        lastNames.add("Morrison");
        lastNames.add("Hansen");
        lastNames.add("Fernandez");
        lastNames.add("Garza");
        lastNames.add("Harvey");
        lastNames.add("Little");
        lastNames.add("Burton");
        lastNames.add("Stanley");
        lastNames.add("Nguyen");
        lastNames.add("George");
        lastNames.add("Jacobs");
        lastNames.add("Reid");
        lastNames.add("Kim");
        lastNames.add("Fuller");
        lastNames.add("Lynch");
        lastNames.add("Dean");
        lastNames.add("Gilbert");
        lastNames.add("Garrett");
        lastNames.add("Romero");
        lastNames.add("Welch");
        lastNames.add("Larson");
        lastNames.add("Frazier");
        lastNames.add("Burke");
        lastNames.add("Hanson");
        lastNames.add("Day");
        lastNames.add("Mendoza");
        lastNames.add("Moreno");
        lastNames.add("Bowman");
        lastNames.add("Medina");
        lastNames.add("Fowler");
        lastNames.add("Brewer");
        lastNames.add("Hoffman");
        lastNames.add("Carlson");
        lastNames.add("Silva");
        lastNames.add("Pearson");
        lastNames.add("Holland");
        lastNames.add("Douglas");
        lastNames.add("Fleming");
        lastNames.add("Jensen");
        lastNames.add("Vargas");
        lastNames.add("Byrd");
        lastNames.add("Davidson");
        lastNames.add("Hopkins");
        lastNames.add("May");
        lastNames.add("Terry");
        lastNames.add("Herrera");
        lastNames.add("Wade");
        lastNames.add("Soto");
        lastNames.add("Walters");
        lastNames.add("Curtis");
        lastNames.add("Neal");
        lastNames.add("Caldwell");
        lastNames.add("Lowe");
        lastNames.add("Jennings");
        lastNames.add("Barnett");
        lastNames.add("Graves");
        lastNames.add("Jimenez");
        lastNames.add("Horton");
        lastNames.add("Shelton");
        lastNames.add("Barrett");
        lastNames.add("Obrien");
        lastNames.add("Castro");
        lastNames.add("Sutton");
        lastNames.add("Gregory");
        lastNames.add("Mckinney");
        lastNames.add("Lucas");
        lastNames.add("Miles");
        lastNames.add("Craig");
        lastNames.add("Rodriquez");
        lastNames.add("Chambers");
        lastNames.add("Holt");
        lastNames.add("Lambert");
        lastNames.add("Fletcher");
        lastNames.add("Watts");
        lastNames.add("Bates");
        lastNames.add("Hale");
        lastNames.add("Rhodes");
        lastNames.add("Pena");
        lastNames.add("Beck");
        lastNames.add("Newman");
        lastNames.add("Haynes");
        lastNames.add("Mcdaniel");
        lastNames.add("Mendez");
        lastNames.add("Bush");
        lastNames.add("Vaughn");
        lastNames.add("Parks");
        lastNames.add("Dawson");
        lastNames.add("Santiago");
        lastNames.add("Norris");
        lastNames.add("Hardy");
        lastNames.add("Love");
        lastNames.add("Steele");
        lastNames.add("Curry");
        lastNames.add("Powers");
        lastNames.add("Schultz");
        lastNames.add("Barker");
        lastNames.add("Guzman");
        lastNames.add("Page");
        lastNames.add("Munoz");
        lastNames.add("Ball");
        lastNames.add("Keller");
        lastNames.add("Chandler");
        lastNames.add("Weber");
        lastNames.add("Leonard");
        lastNames.add("Walsh");
        lastNames.add("Lyons");
        lastNames.add("Ramsey");
        lastNames.add("Wolfe");
        lastNames.add("Schneider");
        lastNames.add("Mullins");
        lastNames.add("Benson");
        lastNames.add("Sharp");
        lastNames.add("Bowen");
        lastNames.add("Daniel");
        lastNames.add("Barber");
        lastNames.add("Cummings");
        lastNames.add("Hines");
        lastNames.add("Baldwin");
        lastNames.add("Griffith");
        lastNames.add("Valdez");
        lastNames.add("Hubbard");
        lastNames.add("Salazar");
        lastNames.add("Reeves");
        lastNames.add("Warner");
        lastNames.add("Stevenson");
        lastNames.add("Burgess");
        lastNames.add("Santos");
        lastNames.add("Tate");
        lastNames.add("Cross");
        lastNames.add("Garner");
        lastNames.add("Mann");
        lastNames.add("Mack");
        lastNames.add("Moss");
        lastNames.add("Thornton");
        lastNames.add("Dennis");
        lastNames.add("Mcgee");
        lastNames.add("Farmer");
        lastNames.add("Delgado");
        lastNames.add("Aguilar");
        lastNames.add("Vega");
        lastNames.add("Glover");
        lastNames.add("Manning");
        lastNames.add("Cohen");
        lastNames.add("Harmon");
        lastNames.add("Rodgers");
        lastNames.add("Robbins");
        lastNames.add("Newton");
        lastNames.add("Todd");
        lastNames.add("Blair");
        lastNames.add("Higgins");
        lastNames.add("Ingram");
        lastNames.add("Reese");
        lastNames.add("Cannon");
        lastNames.add("Strickland");
        lastNames.add("Townsend");
        lastNames.add("Potter");
        lastNames.add("Goodwin");
        lastNames.add("Walton");
        lastNames.add("Rowe");
        lastNames.add("Hampton");
        lastNames.add("Ortega");
        lastNames.add("Patton");
        lastNames.add("Swanson");
        lastNames.add("Joseph");
        lastNames.add("Francis");
        lastNames.add("Goodman");
        lastNames.add("Maldonado");
        lastNames.add("Yates");
        lastNames.add("Becker");
        lastNames.add("Erickson");
        lastNames.add("Hodges");
        lastNames.add("Rios");
        lastNames.add("Conner");
        lastNames.add("Adkins");
        lastNames.add("Webster");
        lastNames.add("Norman");
        lastNames.add("Malone");
        lastNames.add("Hammond");
        lastNames.add("Flowers");
        lastNames.add("Cobb");
        lastNames.add("Moody");
        lastNames.add("Quinn");
        lastNames.add("Blake");
        lastNames.add("Maxwell");
        lastNames.add("Pope");
        lastNames.add("Floyd");
        lastNames.add("Osborne");
        lastNames.add("Paul");
        lastNames.add("Mccarthy");
        lastNames.add("Guerrero");
        lastNames.add("Lindsey");
        lastNames.add("Estrada");
        lastNames.add("Sandoval");
        lastNames.add("Gibbs");
        lastNames.add("Tyler");
        lastNames.add("Gross");
        lastNames.add("Fitzgerald");
        lastNames.add("Stokes");
        lastNames.add("Doyle");
        lastNames.add("Sherman");
        lastNames.add("Saunders");
        lastNames.add("Wise");
        lastNames.add("Colon");
        lastNames.add("Gill");
        lastNames.add("Alvarado");
        lastNames.add("Greer");
        lastNames.add("Padilla");
        lastNames.add("Simon");
        lastNames.add("Waters");
        lastNames.add("Nunez");
        lastNames.add("Ballard");
        lastNames.add("Schwartz");
        lastNames.add("Mcbride");
        lastNames.add("Houston");
        lastNames.add("Christensen");
        lastNames.add("Klein");
        lastNames.add("Pratt");
        lastNames.add("Briggs");
        lastNames.add("Parsons");
        lastNames.add("Mclaughlin");
        lastNames.add("Zimmerman");
        lastNames.add("French");
        lastNames.add("Buchanan");
        lastNames.add("Moran");
        lastNames.add("Copeland");
        lastNames.add("Roy");
        lastNames.add("Pittman");
        lastNames.add("Brady");
        lastNames.add("Mccormick");
        lastNames.add("Holloway");
        lastNames.add("Brock");
        lastNames.add("Poole");
        lastNames.add("Frank");
        lastNames.add("Logan");
        lastNames.add("Owen");
        lastNames.add("Bass");
        lastNames.add("Marsh");
        lastNames.add("Drake");
        lastNames.add("Wong");
        lastNames.add("Jefferson");
        lastNames.add("Park");
        lastNames.add("Morton");
        lastNames.add("Abbott");
        lastNames.add("Sparks");
        lastNames.add("Patrick");
        lastNames.add("Norton");
        lastNames.add("Huff");
        lastNames.add("Clayton");
        lastNames.add("Massey");
        lastNames.add("Lloyd");
        lastNames.add("Figueroa");
        lastNames.add("Carson");
        lastNames.add("Bowers");
        lastNames.add("Roberson");
        lastNames.add("Barton");
        lastNames.add("Tran");
        lastNames.add("Lamb");
        lastNames.add("Harrington");
        lastNames.add("Casey");
        lastNames.add("Boone");
        lastNames.add("Cortez");
        lastNames.add("Clarke");
        lastNames.add("Mathis");
        lastNames.add("Singleton");
        lastNames.add("Wilkins");
        lastNames.add("Cain");
        lastNames.add("Bryan");
        lastNames.add("Underwood");
        lastNames.add("Hogan");
        lastNames.add("Mckenzie");
        lastNames.add("Collier");
        lastNames.add("Luna");
        lastNames.add("Phelps");
        lastNames.add("Mcguire");
        lastNames.add("Allison");
        lastNames.add("Bridges");
        lastNames.add("Wilkerson");
        lastNames.add("Nash");
        lastNames.add("Summers");
        lastNames.add("Atkins");
        lastNames.add("Wilcox");
        lastNames.add("Pitts");
        lastNames.add("Conley");
        lastNames.add("Marquez");
        lastNames.add("Burnett");
        lastNames.add("Richard");
        lastNames.add("Cochran");
        lastNames.add("Chase");
        lastNames.add("Davenport");
        lastNames.add("Hood");
        lastNames.add("Gates");
        lastNames.add("Clay");
        lastNames.add("Ayala");
        lastNames.add("Sawyer");
        lastNames.add("Roman");
        lastNames.add("Vazquez");
        lastNames.add("Dickerson");
        lastNames.add("Hodge");
        lastNames.add("Acosta");
        lastNames.add("Flynn");
        lastNames.add("Espinoza");
        lastNames.add("Nicholson");
        lastNames.add("Monroe");
        lastNames.add("Wolf");
        lastNames.add("Morrow");
        lastNames.add("Kirk");
        lastNames.add("Randall");
        lastNames.add("Anthony");
        lastNames.add("Whitaker");
        lastNames.add("Oconnor");
        lastNames.add("Skinner");
        lastNames.add("Ware");
        lastNames.add("Molina");
        lastNames.add("Kirby");
        lastNames.add("Huffman");
        lastNames.add("Bradford");
        lastNames.add("Charles");
        lastNames.add("Gilmore");
        lastNames.add("Dominguez");
        lastNames.add("Oneal");
        lastNames.add("Bruce");
        lastNames.add("Lang");
        lastNames.add("Combs");
        lastNames.add("Kramer");
        lastNames.add("Heath");
        lastNames.add("Hancock");
        lastNames.add("Gallagher");
        lastNames.add("Gaines");
        lastNames.add("Shaffer");
        lastNames.add("Short");
        lastNames.add("Wiggins");
        lastNames.add("Mathews");
        lastNames.add("Mcclain");
        lastNames.add("Fischer");
        lastNames.add("Wall");
        lastNames.add("Small");
        lastNames.add("Melton");
        lastNames.add("Hensley");
        lastNames.add("Bond");
        lastNames.add("Dyer");
        lastNames.add("Cameron");
        lastNames.add("Grimes");
        lastNames.add("Contreras");
        lastNames.add("Christian");
        lastNames.add("Wyatt");
        lastNames.add("Baxter");
        lastNames.add("Snow");
        lastNames.add("Mosley");
        lastNames.add("Shepherd");
        lastNames.add("Larsen");
        lastNames.add("Hoover");
        lastNames.add("Beasley");
        lastNames.add("Glenn");
        lastNames.add("Petersen");
        lastNames.add("Whitehead");
        lastNames.add("Meyers");
        lastNames.add("Keith");
        lastNames.add("Garrison");
        lastNames.add("Vincent");
        lastNames.add("Shields");
        lastNames.add("Horn");
        lastNames.add("Savage");
        lastNames.add("Olsen");
        lastNames.add("Schroeder");
        lastNames.add("Hartman");
        lastNames.add("Woodard");
        lastNames.add("Mueller");
        lastNames.add("Kemp");
        lastNames.add("Deleon");
        lastNames.add("Booth");
        lastNames.add("Patel");
        lastNames.add("Calhoun");
        lastNames.add("Wiley");
        lastNames.add("Eaton");
        lastNames.add("Cline");
        lastNames.add("Navarro");
        lastNames.add("Harrell");
        lastNames.add("Lester");
        lastNames.add("Humphrey");
        lastNames.add("Parrish");
        lastNames.add("Duran");
        lastNames.add("Hutchinson");
        lastNames.add("Hess");
        lastNames.add("Dorsey");
        lastNames.add("Bullock");
        lastNames.add("Robles");
        lastNames.add("Beard");
        lastNames.add("Dalton");
        lastNames.add("Avila");
        lastNames.add("Vance");
        lastNames.add("Rich");
        lastNames.add("Blackwell");
        lastNames.add("York");
        lastNames.add("Johns");
        lastNames.add("Blankenship");
        lastNames.add("Trevino");
        lastNames.add("Salinas");
        lastNames.add("Campos");
        lastNames.add("Pruitt");
        lastNames.add("Moses");
        lastNames.add("Callahan");
        lastNames.add("Golden");
        lastNames.add("Montoya");
        lastNames.add("Hardin");
        lastNames.add("Guerra");
        lastNames.add("Mcdowell");
        lastNames.add("Carey");
        lastNames.add("Stafford");
        lastNames.add("Gallegos");
        lastNames.add("Henson");
        lastNames.add("Wilkinson");
        lastNames.add("Booker");
        lastNames.add("Merritt");
        lastNames.add("Miranda");
        lastNames.add("Atkinson");
        lastNames.add("Orr");
        lastNames.add("Decker");
        lastNames.add("Hobbs");
        lastNames.add("Preston");
        lastNames.add("Tanner");
        lastNames.add("Knox");
        lastNames.add("Pacheco");
        lastNames.add("Stephenson");
        lastNames.add("Glass");
        lastNames.add("Rojas");
        lastNames.add("Serrano");
        lastNames.add("Marks");
        lastNames.add("Hickman");
        lastNames.add("English");
        lastNames.add("Sweeney");
        lastNames.add("Strong");
        lastNames.add("Prince");
        lastNames.add("Mcclure");
        lastNames.add("Conway");
        lastNames.add("Walter");
        lastNames.add("Roth");
        lastNames.add("Maynard");
        lastNames.add("Farrell");
        lastNames.add("Lowery");
        lastNames.add("Hurst");
        lastNames.add("Nixon");
        lastNames.add("Weiss");
        lastNames.add("Trujillo");
        lastNames.add("Ellison");
        lastNames.add("Sloan");
        lastNames.add("Juarez");
        lastNames.add("Winters");
        lastNames.add("Mclean");
        lastNames.add("Randolph");
        lastNames.add("Leon");
        lastNames.add("Boyer");
        lastNames.add("Villarreal");
        lastNames.add("Mccall");
        lastNames.add("Gentry");
        lastNames.add("Carrillo");
        lastNames.add("Kent");
        lastNames.add("Ayers");
        lastNames.add("Lara");
        lastNames.add("Shannon");
        lastNames.add("Sexton");
        lastNames.add("Pace");
        lastNames.add("Hull");
        lastNames.add("Leblanc");
        lastNames.add("Browning");
        lastNames.add("Velasquez");
        lastNames.add("Leach");
        lastNames.add("Chang");
        lastNames.add("House");
        lastNames.add("Sellers");
        lastNames.add("Herring");
        lastNames.add("Noble");
        lastNames.add("Foley");
        lastNames.add("Bartlett");
        lastNames.add("Mercado");
        lastNames.add("Landry");
        lastNames.add("Durham");
        lastNames.add("Walls");
        lastNames.add("Barr");
        lastNames.add("Mckee");
        lastNames.add("Bauer");
        lastNames.add("Rivers");
        lastNames.add("Everett");
        lastNames.add("Bradshaw");
        lastNames.add("Pugh");
        lastNames.add("Velez");
        lastNames.add("Rush");
        lastNames.add("Estes");
        lastNames.add("Dodson");
        lastNames.add("Morse");
        lastNames.add("Sheppard");
        lastNames.add("Weeks");
        lastNames.add("Camacho");
        lastNames.add("Bean");
        lastNames.add("Barron");
        lastNames.add("Livingston");
        lastNames.add("Middleton");
        lastNames.add("Spears");
        lastNames.add("Branch");
        lastNames.add("Blevins");
        lastNames.add("Chen");
        lastNames.add("Kerr");
        lastNames.add("Mcconnell");
        lastNames.add("Hatfield");
        lastNames.add("Harding");
        lastNames.add("Ashley");
        lastNames.add("Solis");
        lastNames.add("Herman");
        lastNames.add("Frost");
        lastNames.add("Giles");
        lastNames.add("Blackburn");
        lastNames.add("William");
        lastNames.add("Pennington");
        lastNames.add("Woodward");
        lastNames.add("Finley");
        lastNames.add("Mcintosh");
        lastNames.add("Koch");
        lastNames.add("Best");
        lastNames.add("Solomon");
        lastNames.add("Mccullough");
        lastNames.add("Dudley");
        lastNames.add("Nolan");
        lastNames.add("Blanchard");
        lastNames.add("Rivas");
        lastNames.add("Brennan");
        lastNames.add("Mejia");
        lastNames.add("Kane");
        lastNames.add("Benton");
        lastNames.add("Joyce");
        lastNames.add("Buckley");
        lastNames.add("Haley");
        lastNames.add("Valentine");
        lastNames.add("Maddox");
        lastNames.add("Russo");
        lastNames.add("Mcknight");
        lastNames.add("Buck");
        lastNames.add("Moon");
        lastNames.add("Mcmillan");
        lastNames.add("Crosby");
        lastNames.add("Berg");
        lastNames.add("Dotson");
        lastNames.add("Mays");
        lastNames.add("Roach");
        lastNames.add("Church");
        lastNames.add("Chan");
        lastNames.add("Richmond");
        lastNames.add("Meadows");
        lastNames.add("Faulkner");
        lastNames.add("Oneill");
        lastNames.add("Knapp");
        lastNames.add("Kline");
        lastNames.add("Barry");
        lastNames.add("Ochoa");
        lastNames.add("Jacobson");
        lastNames.add("Gay");
        lastNames.add("Avery");
        lastNames.add("Hendricks");
        lastNames.add("Horne");
        lastNames.add("Shepard");
        lastNames.add("Hebert");
        lastNames.add("Cherry");
        lastNames.add("Cardenas");
        lastNames.add("Mcintyre");
        lastNames.add("Whitney");
        lastNames.add("Waller");
        lastNames.add("Holman");
        lastNames.add("Donaldson");
        lastNames.add("Cantu");
        lastNames.add("Terrell");
        lastNames.add("Morin");
        lastNames.add("Gillespie");
        lastNames.add("Fuentes");
        lastNames.add("Tillman");
        lastNames.add("Sanford");
        lastNames.add("Bentley");
        lastNames.add("Peck");
        lastNames.add("Key");
        lastNames.add("Salas");
        lastNames.add("Rollins");
        lastNames.add("Gamble");
        lastNames.add("Dickson");
        lastNames.add("Battle");
        lastNames.add("Santana");
        lastNames.add("Cabrera");
        lastNames.add("Cervantes");
        lastNames.add("Howe");
        lastNames.add("Hinton");
        lastNames.add("Hurley");
        lastNames.add("Spence");
        lastNames.add("Zamora");
        lastNames.add("Yang");
        lastNames.add("Mcneil");
        lastNames.add("Suarez");
        lastNames.add("Case");
        lastNames.add("Petty");
        lastNames.add("Gould");
        lastNames.add("Mcfarland");
        lastNames.add("Sampson");
        lastNames.add("Carver");
        lastNames.add("Bray");
        lastNames.add("Rosario");
        lastNames.add("Macdonald");
        lastNames.add("Stout");
        lastNames.add("Hester");
        lastNames.add("Melendez");
        lastNames.add("Dillon");
        lastNames.add("Farley");
        lastNames.add("Hopper");
        lastNames.add("Galloway");
        lastNames.add("Potts");
        lastNames.add("Bernard");
        lastNames.add("Joyner");
        lastNames.add("Stein");
        lastNames.add("Aguirre");
        lastNames.add("Osborn");
        lastNames.add("Mercer");
        lastNames.add("Bender");
        lastNames.add("Franco");
        lastNames.add("Rowland");
        lastNames.add("Sykes");
        lastNames.add("Benjamin");
        lastNames.add("Travis");
        lastNames.add("Pickett");
        lastNames.add("Crane");
        lastNames.add("Sears");
        lastNames.add("Mayo");
        lastNames.add("Dunlap");
        lastNames.add("Hayden");
        lastNames.add("Wilder");
        lastNames.add("Mckay");
        lastNames.add("Coffey");
        lastNames.add("Mccarty");
        lastNames.add("Ewing");
        lastNames.add("Cooley");
        lastNames.add("Vaughan");
        lastNames.add("Bonner");
        lastNames.add("Cotton");
        lastNames.add("Holder");
        lastNames.add("Stark");
        lastNames.add("Ferrell");
        lastNames.add("Cantrell");
        lastNames.add("Fulton");
        lastNames.add("Lynn");
        lastNames.add("Lott");
        lastNames.add("Calderon");
        lastNames.add("Rosa");
        lastNames.add("Pollard");
        lastNames.add("Hooper");
        lastNames.add("Burch");
        lastNames.add("Mullen");
        lastNames.add("Fry");
        lastNames.add("Riddle");
        lastNames.add("Levy");
        lastNames.add("David");
        lastNames.add("Duke");
        lastNames.add("Odonnell");
        lastNames.add("Guy");
        lastNames.add("Michael");
        lastNames.add("Britt");
        lastNames.add("Frederick");
        lastNames.add("Daugherty");
        lastNames.add("Berger");
        lastNames.add("Dillard");
        lastNames.add("Alston");
        lastNames.add("Jarvis");
        lastNames.add("Frye");
        lastNames.add("Riggs");
        lastNames.add("Chaney");
        lastNames.add("Odom");
        lastNames.add("Duffy");
        lastNames.add("Fitzpatrick");
        lastNames.add("Valenzuela");
        lastNames.add("Merrill");
        lastNames.add("Mayer");
        lastNames.add("Alford");
        lastNames.add("Mcpherson");
        lastNames.add("Acevedo");
        lastNames.add("Donovan");
        lastNames.add("Barrera");
        lastNames.add("Albert");
        lastNames.add("Cote");
        lastNames.add("Reilly");
        lastNames.add("Compton");
        lastNames.add("Raymond");
        lastNames.add("Mooney");
        lastNames.add("Mcgowan");
        lastNames.add("Craft");
        lastNames.add("Cleveland");
        lastNames.add("Clemons");
        lastNames.add("Wynn");
        lastNames.add("Nielsen");
        lastNames.add("Baird");
        lastNames.add("Stanton");
        lastNames.add("Snider");
        lastNames.add("Rosales");
        lastNames.add("Bright");
        lastNames.add("Witt");
        lastNames.add("Stuart");
        lastNames.add("Hays");
        lastNames.add("Holden");
        lastNames.add("Rutledge");
        lastNames.add("Kinney");
        lastNames.add("Clements");
        lastNames.add("Castaneda");
        lastNames.add("Slater");
        lastNames.add("Hahn");
        lastNames.add("Emerson");
        lastNames.add("Conrad");
        lastNames.add("Burks");
        lastNames.add("Delaney");
        lastNames.add("Pate");
        lastNames.add("Lancaster");
        lastNames.add("Sweet");
        lastNames.add("Justice");
        lastNames.add("Tyson");
        lastNames.add("Sharpe");
        lastNames.add("Whitfield");
        lastNames.add("Talley");
        lastNames.add("Macias");
        lastNames.add("Irwin");
        lastNames.add("Burris");
        lastNames.add("Ratliff");
        lastNames.add("Mccray");
        lastNames.add("Madden");
        lastNames.add("Kaufman");
        lastNames.add("Beach");
        lastNames.add("Goff");
        lastNames.add("Cash");
        lastNames.add("Bolton");
        lastNames.add("Mcfadden");
        lastNames.add("Levine");
        lastNames.add("Good");
        lastNames.add("Byers");
        lastNames.add("Kirkland");
        lastNames.add("Kidd");
        lastNames.add("Workman");
        lastNames.add("Carney");
        lastNames.add("Dale");
        lastNames.add("Mcleod");
        lastNames.add("Holcomb");
        lastNames.add("England");
        lastNames.add("Finch");
        lastNames.add("Head");
        lastNames.add("Burt");
        lastNames.add("Hendrix");
        lastNames.add("Sosa");
        lastNames.add("Haney");
        lastNames.add("Franks");
        lastNames.add("Sargent");
        lastNames.add("Nieves");
        lastNames.add("Downs");
        lastNames.add("Rasmussen");
        lastNames.add("Bird");
        lastNames.add("Hewitt");
        lastNames.add("Lindsay");
        lastNames.add("Le");
        lastNames.add("Foreman");
        lastNames.add("Valencia");
        lastNames.add("Oneil");
        lastNames.add("Delacruz");
        lastNames.add("Vinson");
        lastNames.add("Dejesus");
        lastNames.add("Hyde");
        lastNames.add("Forbes");
        lastNames.add("Gilliam");
        lastNames.add("Guthrie");
        lastNames.add("Wooten");
        lastNames.add("Huber");
        lastNames.add("Barlow");
        lastNames.add("Boyle");
        lastNames.add("Mcmahon");
        lastNames.add("Buckner");
        lastNames.add("Rocha");
        lastNames.add("Puckett");
        lastNames.add("Langley");
        lastNames.add("Knowles");
        lastNames.add("Cooke");
        lastNames.add("Velazquez");
        lastNames.add("Whitley");
        lastNames.add("Noel");
        lastNames.add("Vang");
        return lastNames.get(new Random().nextInt(lastNames.size()));
    }

    static String randomName() {
        ArrayList<String> names = new ArrayList<>();
        names.add("Duncan");
        names.add("Stanton");
        names.add("Elliot");
        names.add("Courtney");
        names.add("Kendall");
        names.add("Tuan");
        names.add("Sang");
        names.add("Wayne");
        names.add("Abe");
        names.add("Nicky");
        names.add("Jeffery");
        names.add("Lanny");
        names.add("Abdul");
        names.add("Roland");
        names.add("Sanford");
        names.add("Ashley");
        names.add("Lazaro");
        names.add("Steven");
        names.add("Virgilio");
        names.add("Kristopher");
        names.add("Roberto");
        names.add("Ricardo");
        names.add("Marquis");
        names.add("Vicente");
        names.add("Lorenzo");
        names.add("Stan");
        names.add("Monty");
        names.add("Tracey");
        names.add("Efrain");
        names.add("Long");
        names.add("Clay");
        names.add("Darrick");
        names.add("Stanley");
        names.add("Allan");
        names.add("Angelo");
        names.add("Isaias");
        names.add("Ali");
        names.add("Brian");
        names.add("Jaime");
        names.add("Les");
        names.add("Sherwood");
        names.add("Edmond");
        names.add("Joesph");
        names.add("Winfred");
        names.add("Len");
        names.add("Eusebio");
        names.add("Lonnie");
        names.add("Santos");
        names.add("Ian");
        names.add("Miguel");
        names.add("Reatha");
        names.add("Syreeta");
        names.add("Jenny");
        names.add("Yuette");
        names.add("Phoebe");
        names.add("Joy");
        names.add("Denyse");
        names.add("Rachele");
        names.add("Ramonita");
        names.add("Shaunda");
        names.add("Sharon");
        names.add("Christeen");
        names.add("Phuong");
        names.add("Daniell");
        names.add("Chanda");
        names.add("Ninfa");
        names.add("Elise");
        names.add("Annabelle");
        names.add("Debrah");
        names.add("Christene");
        names.add("Madalene");
        names.add("Letty");
        names.add("Phung");
        names.add("Kerrie");
        names.add("Louella");
        names.add("Onita");
        names.add("Berneice");
        names.add("Nguyet");
        names.add("Freeda");
        names.add("Davina");
        names.add("Roseanne");
        names.add("Janetta");
        names.add("Mikki");
        names.add("Jaunita");
        names.add("Rikki");
        names.add("Alysia");
        names.add("Staci");
        names.add("Lavone");
        names.add("Margarita");
        names.add("Wai");
        names.add("Laine");
        names.add("Alina");
        names.add("Eustolia");
        names.add("Leonida");
        names.add("Elma");
        names.add("Shu");
        names.add("Annmarie");
        names.add("Sanora");
        names.add("Candance");
        names.add("Kimi");
        return names.get(new Random().nextInt(names.size()));
    }

    static String randomAnimal(){
        ArrayList<String> animals = new ArrayList<>();

        animals.add("Aardvark");
        animals.add("Abyssinian");
        animals.add("Adelie Penguin");
        animals.add("Affenpinscher");
        animals.add("Afghan Hound");
        animals.add("African Bush Elephant");
        animals.add("African Civet");
        animals.add("African Clawed Frog");
        animals.add("African Forest Elephant");
        animals.add("African Palm Civet");
        animals.add("African Penguin");
        animals.add("African Tree Toad");
        animals.add("African Wild Dog");
        animals.add("Ainu Dog");
        animals.add("Airedale Terrier");
        animals.add("Akbash");
        animals.add("Akita");
        animals.add("Alaskan Malamute");
        animals.add("Albatross");
        animals.add("Aldabra Giant Tortoise");
        animals.add("Alligator");
        animals.add("Alpine Dachsbracke");
        animals.add("American Bulldog");
        animals.add("American Cocker Spaniel");
        animals.add("American Coonhound");
        animals.add("American Eskimo Dog");
        animals.add("American Foxhound");
        animals.add("American Pit Bull Terrier");
        animals.add("American Staffordshire Terrier");
        animals.add("American Water Spaniel");
        animals.add("Anatolian Shepherd Dog");
        animals.add("Angelfish");
        animals.add("Ant");
        animals.add("Anteater");
        animals.add("Antelope");
        animals.add("Appenzeller Dog");
        animals.add("Arctic Fox");
        animals.add("Arctic Hare");
        animals.add("Arctic Wolf");
        animals.add("Armadillo");
        animals.add("Asian Elephant");
        animals.add("Asian Giant Hornet");
        animals.add("Asian Palm Civet");
        animals.add("Asiatic Black Bear");
        animals.add("Australian Cattle Dog");
        animals.add("Australian Kelpie Dog");
        animals.add("Australian Mist");
        animals.add("Australian Shepherd");
        animals.add("Australian Terrier");
        animals.add("Avocet");
        animals.add("Axolotl");
        animals.add("Aye Aye");
        animals.add("Baboon");
        animals.add("Bactrian Camel");
        animals.add("Badger");
        animals.add("Balinese");
        animals.add("Banded Palm Civet");
        animals.add("Bandicoot");
        animals.add("Barb");
        animals.add("Barn Owl");
        animals.add("Barnacle");
        animals.add("Barracuda");
        animals.add("Basenji Dog");
        animals.add("Basking Shark");
        animals.add("Basset Hound");
        animals.add("Bat");
        animals.add("Bavarian Mountain Hound");
        animals.add("Beagle");
        animals.add("Bear");
        animals.add("Bearded Collie");
        animals.add("Bearded Dragon");
        animals.add("Beaver");
        animals.add("Bedlington Terrier");
        animals.add("Beetle");
        animals.add("Bengal Tiger");
        animals.add("Bernese Mountain Dog");
        animals.add("Bichon Frise");
        animals.add("Binturong");
        animals.add("Bird");
        animals.add("Birds Of Paradise");
        animals.add("Birman");
        animals.add("Bison");
        animals.add("Black Bear");
        animals.add("Black Rhinoceros");
        animals.add("Black Russian Terrier");
        animals.add("Black Widow Spider");
        animals.add("Bloodhound");
        animals.add("Blue Lacy Dog");
        animals.add("Blue Whale");
        animals.add("Bluetick Coonhound");
        animals.add("Bobcat");
        animals.add("Bolognese Dog");
        animals.add("Bombay");
        animals.add("Bongo");
        animals.add("Bonobo");
        animals.add("Booby");
        animals.add("Border Collie");
        animals.add("Border Terrier");
        animals.add("Bornean Orang-utan");
        animals.add("Borneo Elephant");
        animals.add("Boston Terrier");
        animals.add("Bottle Nosed Dolphin");
        animals.add("Boxer Dog");
        animals.add("Boykin Spaniel");
        animals.add("Brazilian Terrier");
        animals.add("Brown Bear");
        animals.add("Budgerigar");
        animals.add("Buffalo");
        animals.add("Bull Mastiff");
        animals.add("Bull Shark");
        animals.add("Bull Terrier");
        animals.add("Bulldog");
        animals.add("Bullfrog");
        animals.add("Bumble Bee");
        animals.add("Burmese");
        animals.add("Burrowing Frog");
        animals.add("Butterfly");
        animals.add("Butterfly Fish");
        animals.add("Caiman");
        animals.add("Caiman Lizard");
        animals.add("Cairn Terrier");
        animals.add("Camel");
        animals.add("Canaan Dog");
        animals.add("Capybara");
        animals.add("Caracal");
        animals.add("Carolina Dog");
        animals.add("Cassowary");
        animals.add("Cat");
        animals.add("Caterpillar");
        animals.add("Catfish");
        animals.add("Cavalier King Charles Spaniel");
        animals.add("Centipede");
        animals.add("Cesky Fousek");
        animals.add("Chameleon");
        animals.add("Chamois");
        animals.add("Cheetah");
        animals.add("Chesapeake Bay Retriever");
        animals.add("Chicken");
        animals.add("Chihuahua");
        animals.add("Chimpanzee");
        animals.add("Chinchilla");
        animals.add("Chinese Crested Dog");
        animals.add("Chinook");
        animals.add("Chinstrap Penguin");
        animals.add("Chipmunk");
        animals.add("Chow Chow");
        animals.add("Cichlid");
        animals.add("Clouded Leopard");
        animals.add("Clown Fish");
        animals.add("Clumber Spaniel");
        animals.add("Coati");
        animals.add("Cockroach");
        animals.add("Collared Peccary");
        animals.add("Collie");
        animals.add("Common Buzzard");
        animals.add("Common Frog");
        animals.add("Common Loon");
        animals.add("Common Toad");
        animals.add("Coral");
        animals.add("Cottontop Tamarin");
        animals.add("Cougar");
        animals.add("Cow");
        animals.add("Coyote");
        animals.add("Crab");
        animals.add("Crab-Eating Macaque");
        animals.add("Crane");
        animals.add("Crested Penguin");
        animals.add("Crocodile");
        animals.add("Cross River Gorilla");
        animals.add("Curly Coated Retriever");
        animals.add("Cuscus");
        animals.add("Cuttlefish");
        animals.add("Dachshund");
        animals.add("Dalmatian");
        animals.add("Darwin's Frog");
        animals.add("Deer");
        animals.add("Desert Tortoise");
        animals.add("Deutsche Bracke");
        animals.add("Dhole");
        animals.add("Dingo");
        animals.add("Discus");
        animals.add("Doberman Pinscher");
        animals.add("Dodo");
        animals.add("Dog");
        animals.add("Dogo Argentino");
        animals.add("Dogue De Bordeaux");
        animals.add("Dolphin");
        animals.add("Donkey");
        animals.add("Dormouse");
        animals.add("Dragonfly");
        animals.add("Drever");
        animals.add("Duck");
        animals.add("Dugong");
        animals.add("Dunker");
        animals.add("Dusky Dolphin");
        animals.add("Dwarf Crocodile");
        animals.add("Eagle");
        animals.add("Earwig");
        animals.add("Eastern Gorilla");
        animals.add("Eastern Lowland Gorilla");
        animals.add("Echidna");
        animals.add("Edible Frog");
        animals.add("Egyptian Mau");
        animals.add("Electric Eel");
        animals.add("Elephant");
        animals.add("Elephant Seal");
        animals.add("Elephant Shrew");
        animals.add("Emperor Penguin");
        animals.add("Emperor Tamarin");
        animals.add("Emu");
        animals.add("English Cocker Spaniel");
        animals.add("English Shepherd");
        animals.add("English Springer Spaniel");
        animals.add("Entlebucher Mountain Dog");
        animals.add("Epagneul Pont Audemer");
        animals.add("Eskimo Dog");
        animals.add("Estrela Mountain Dog");
        animals.add("Falcon");
        animals.add("Fennec Fox");
        animals.add("Ferret");
        animals.add("Field Spaniel");
        animals.add("Fin Whale");
        animals.add("Finnish Spitz");
        animals.add("Fire-Bellied Toad");
        animals.add("Fish");
        animals.add("Fishing Cat");
        animals.add("Flamingo");
        animals.add("Flat Coat Retriever");
        animals.add("Flounder");
        animals.add("Fly");
        animals.add("Flying Squirrel");
        animals.add("Fossa");
        animals.add("Fox");
        animals.add("Fox Terrier");
        animals.add("French Bulldog");
        animals.add("Frigatebird");
        animals.add("Frilled Lizard");
        animals.add("Frog");
        animals.add("Fur Seal");
        animals.add("Galapagos Penguin");
        animals.add("Galapagos Tortoise");
        animals.add("Gar");
        animals.add("Gecko");
        animals.add("Gentoo Penguin");
        animals.add("Geoffroys Tamarin");
        animals.add("Gerbil");
        animals.add("German Pinscher");
        animals.add("German Shepherd");
        animals.add("Gharial");
        animals.add("Giant African Land Snail");
        animals.add("Giant Clam");
        animals.add("Giant Panda Bear");
        animals.add("Giant Schnauzer");
        animals.add("Gibbon");
        animals.add("Gila Monster");
        animals.add("Giraffe");
        animals.add("Glass Lizard");
        animals.add("Glow Worm");
        animals.add("Goat");
        animals.add("Golden Lion Tamarin");
        animals.add("Golden Oriole");
        animals.add("Golden Retriever");
        animals.add("Goose");
        animals.add("Gopher");
        animals.add("Gorilla");
        animals.add("Grasshopper");
        animals.add("Great Dane");
        animals.add("Great White Shark");
        animals.add("Greater Swiss Mountain Dog");
        animals.add("Green Bee-Eater");
        animals.add("Greenland Dog");
        animals.add("Grey Mouse Lemur");
        animals.add("Grey Reef Shark");
        animals.add("Grey Seal");
        animals.add("Greyhound");
        animals.add("Grizzly Bear");
        animals.add("Grouse");
        animals.add("Guinea Fowl");
        animals.add("Guinea Pig");
        animals.add("Guppy");
        animals.add("Hammerhead Shark");
        animals.add("Hamster");
        animals.add("Hare");
        animals.add("Harrier");
        animals.add("Havanese");
        animals.add("Hedgehog");
        animals.add("Hercules Beetle");
        animals.add("Hermit Crab");
        animals.add("Heron");
        animals.add("Highland Cattle");
        animals.add("Himalayan");
        animals.add("Hippopotamus");
        animals.add("Honey Bee");
        animals.add("Horn Shark");
        animals.add("Horned Frog");
        animals.add("Horse");
        animals.add("Horseshoe Crab");
        animals.add("Howler Monkey");
        animals.add("Human");
        animals.add("Humboldt Penguin");
        animals.add("Hummingbird");
        animals.add("Humpback Whale");
        animals.add("Hyena");
        animals.add("Ibis");
        animals.add("Ibizan Hound");
        animals.add("Iguana");
        animals.add("Impala");
        animals.add("Indian Elephant");
        animals.add("Indian Palm Squirrel");
        animals.add("Indian Rhinoceros");
        animals.add("Indian Star Tortoise");
        animals.add("Indochinese Tiger");
        animals.add("Indri");
        animals.add("Insect");
        animals.add("Irish Setter");
        animals.add("Irish WolfHound");
        animals.add("Jack Russel");
        animals.add("Jackal");
        animals.add("Jaguar");
        animals.add("Japanese Chin");
        animals.add("Japanese Macaque");
        animals.add("Javan Rhinoceros");
        animals.add("Javanese");
        animals.add("Jellyfish");
        animals.add("Kakapo");
        animals.add("Kangaroo");
        animals.add("Keel Billed Toucan");
        animals.add("Killer Whale");
        animals.add("King Crab");
        animals.add("King Penguin");
        animals.add("Kingfisher");
        animals.add("Kiwi");
        animals.add("Koala");
        animals.add("Komodo Dragon");
        animals.add("Kudu");
        animals.add("Labradoodle");
        animals.add("Labrador Retriever");
        animals.add("Ladybird");
        animals.add("Leaf-Tailed Gecko");
        animals.add("Lemming");
        animals.add("Lemur");
        animals.add("Leopard");
        animals.add("Leopard Cat");
        animals.add("Leopard Seal");
        animals.add("Leopard Tortoise");
        animals.add("Liger");
        animals.add("Lion");
        animals.add("Lionfish");
        animals.add("Little Penguin");
        animals.add("Lizard");
        animals.add("Llama");
        animals.add("Lobster");
        animals.add("Long-Eared Owl");
        animals.add("Lynx");
        animals.add("Macaroni Penguin");
        animals.add("Macaw");
        animals.add("Magellanic Penguin");
        animals.add("Magpie");
        animals.add("Maine Coon");
        animals.add("Malayan Civet");
        animals.add("Malayan Tiger");
        animals.add("Maltese");
        animals.add("Manatee");
        animals.add("Mandrill");
        animals.add("Manta Ray");
        animals.add("Marine Toad");
        animals.add("Markhor");
        animals.add("Marsh Frog");
        animals.add("Masked Palm Civet");
        animals.add("Mastiff");
        animals.add("Mayfly");
        animals.add("Meerkat");
        animals.add("Millipede");
        animals.add("Minke Whale");
        animals.add("Mole");
        animals.add("Molly");
        animals.add("Mongoose");
        animals.add("Mongrel");
        animals.add("Monitor Lizard");
        animals.add("Monkey");
        animals.add("Monte Iberia Eleuth");
        animals.add("Moorhen");
        animals.add("Moose");
        animals.add("Moray Eel");
        animals.add("Moth");
        animals.add("Mountain Gorilla");
        animals.add("Mountain Lion");
        animals.add("Mouse");
        animals.add("Mule");
        animals.add("Neanderthal");
        animals.add("Neapolitan Mastiff");
        animals.add("Newfoundland");
        animals.add("Newt");
        animals.add("Nightingale");
        animals.add("Norfolk Terrier");
        animals.add("Norwegian Forest");
        animals.add("Numbat");
        animals.add("Nurse Shark");
        animals.add("Ocelot");
        animals.add("Octopus");
        animals.add("Okapi");
        animals.add("Old English Sheepdog");
        animals.add("Olm");
        animals.add("Opossum");
        animals.add("Orang-utan");
        animals.add("Ostrich");
        animals.add("Otter");
        animals.add("Oyster");
        animals.add("Pademelon");
        animals.add("Panther");
        animals.add("Parrot");
        animals.add("Patas Monkey");
        animals.add("Peacock");
        animals.add("Pekingese");
        animals.add("Pelican");
        animals.add("Penguin");
        animals.add("Persian");
        animals.add("Pheasant");
        animals.add("Pied Tamarin");
        animals.add("Pig");
        animals.add("Pika");
        animals.add("Pike");
        animals.add("Pink Fairy Armadillo");
        animals.add("Piranha");
        animals.add("Platypus");
        animals.add("Pointer");
        animals.add("Poison Dart Frog");
        animals.add("Polar Bear");
        animals.add("Pond Skater");
        animals.add("Poodle");
        animals.add("Pool Frog");
        animals.add("Porcupine");
        animals.add("Possum");
        animals.add("Prawn");
        animals.add("Proboscis Monkey");
        animals.add("Puffer Fish");
        animals.add("Puffin");
        animals.add("Pug");
        animals.add("Puma");
        animals.add("Purple Emperor");
        animals.add("Puss Moth");
        animals.add("Pygmy Hippopotamus");
        animals.add("Pygmy Marmoset");
        animals.add("Quail");
        animals.add("Quetzal");
        animals.add("Quokka");
        animals.add("Quoll");
        animals.add("Rabbit");
        animals.add("Raccoon");
        animals.add("Raccoon Dog");
        animals.add("Radiated Tortoise");
        animals.add("Ragdoll");
        animals.add("Rat");
        animals.add("Rattlesnake");
        animals.add("Red Knee Tarantula");
        animals.add("Red Panda");
        animals.add("Red Wolf");
        animals.add("Red-handed Tamarin");
        animals.add("Reindeer");
        animals.add("Rhinoceros");
        animals.add("River Dolphin");
        animals.add("River Turtle");
        animals.add("Robin");
        animals.add("Rock Hyrax");
        animals.add("Rockhopper Penguin");
        animals.add("Roseate Spoonbill");
        animals.add("Rottweiler");
        animals.add("Royal Penguin");
        animals.add("Russian Blue");
        animals.add("Sabre-Toothed Tiger");
        animals.add("Saint Bernard");
        animals.add("Salamander");
        animals.add("Sand Lizard");
        animals.add("Saola");
        animals.add("Scorpion");
        animals.add("Scorpion Fish");
        animals.add("Sea Dragon");
        animals.add("Sea Lion");
        animals.add("Sea Otter");
        animals.add("Sea Slug");
        animals.add("Sea Squirt");
        animals.add("Sea Turtle");
        animals.add("Sea Urchin");
        animals.add("Seahorse");
        animals.add("Seal");
        animals.add("Serval");
        animals.add("Sheep");
        animals.add("Shih Tzu");
        animals.add("Shrimp");
        animals.add("Siamese");
        animals.add("Siamese Fighting Fish");
        animals.add("Siberian");
        animals.add("Siberian Husky");
        animals.add("Siberian Tiger");
        animals.add("Silver Dollar");
        animals.add("Skunk");
        animals.add("Sloth");
        animals.add("Slow Worm");
        animals.add("Snail");
        animals.add("Snake");
        animals.add("Snapping Turtle");
        animals.add("Snowshoe");
        animals.add("Snowy Owl");
        animals.add("Somali");
        animals.add("South China Tiger");
        animals.add("Spadefoot Toad");
        animals.add("Sparrow");
        animals.add("Spectacled Bear");
        animals.add("Sperm Whale");
        animals.add("Spider Monkey");
        animals.add("Spiny Dogfish");
        animals.add("Sponge");
        animals.add("Squid");
        animals.add("Squirrel");
        animals.add("Squirrel Monkey");
        animals.add("Sri Lankan Elephant");
        animals.add("Staffordshire Bull Terrier");
        animals.add("Stag Beetle");
        animals.add("Starfish");
        animals.add("Stellers Sea Cow");
        animals.add("Stick Insect");
        animals.add("Stingray");
        animals.add("Stoat");
        animals.add("Striped Rocket Frog");
        animals.add("Sumatran Elephant");
        animals.add("Sumatran Orang-utan");
        animals.add("Sumatran Rhinoceros");
        animals.add("Sumatran Tiger");
        animals.add("Sun Bear");
        animals.add("Swan");
        animals.add("Tang");
        animals.add("Tapanuli Orang-utan");
        animals.add("Tapir");
        animals.add("Tarsier");
        animals.add("Tasmanian Devil");
        animals.add("Tawny Owl");
        animals.add("Termite");
        animals.add("Tetra");
        animals.add("Thorny Devil");
        animals.add("Tibetan Mastiff");
        animals.add("Tiffany");
        animals.add("Tiger");
        animals.add("Tiger Salamander");
        animals.add("Tiger Shark");
        animals.add("Tortoise");
        animals.add("Toucan");
        animals.add("Tree Frog");
        animals.add("Tropicbird");
        animals.add("Tuatara");
        animals.add("Turkey");
        animals.add("Turkish Angora");
        animals.add("Uakari");
        animals.add("Uguisu");
        animals.add("Umbrellabird");
        animals.add("Vampire Bat");
        animals.add("Vervet Monkey");
        animals.add("Vulture");
        animals.add("Wallaby");
        animals.add("Walrus");
        animals.add("Warthog");
        animals.add("Wasp");
        animals.add("Water Buffalo");
        animals.add("Water Dragon");
        animals.add("Water Vole");
        animals.add("Weasel");
        animals.add("Welsh Corgi");
        animals.add("West Highland Terrier");
        animals.add("Western Gorilla");
        animals.add("Western Lowland Gorilla");
        animals.add("Whale Shark");
        animals.add("Whippet");
        animals.add("White Faced Capuchin");
        animals.add("White Rhinoceros");
        animals.add("White Tiger");
        animals.add("Wild Boar");
        animals.add("Wildebeest");
        animals.add("Wolf");
        animals.add("Wolverine");
        animals.add("Wombat");
        animals.add("Woodlouse");
        animals.add("Woodpecker");
        animals.add("Woolly Mammoth");
        animals.add("Woolly Monkey");
        animals.add("Wrasse");
        animals.add("Yak");
        animals.add("Yellow-Eyed Penguin");
        animals.add("Yorkshire Terrier");
        animals.add("Zebra");
        animals.add("Zebra Shark");
        animals.add("Zebu");
        animals.add("Zonkey");
        animals.add("Zorse");
        return animals.get(new Random().nextInt(animals.size()));
    }
}